Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public int EngineerId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set;}
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int EngineerId { get; set; }
    public int MachineId{ get; set; }
    public virtual Engineer Engineer { get; set; }
    public virtual Machine Machine {get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public virtual DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachine { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
namespace Factory.Models
{
  public class Machine
  {
    public int MachineId { get; set; }
    public string Name { get; set; }
    public string Description {get; set;}
    public virtual ICollection<EngineerMachine> JoinEntities { get; }
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Factory.Controllers
{
  public class EngineerController : Controller
  {
    private readonly FactoryContext _db;
    public EngineerController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
      .Include(engineer => engineer.JoinEntities)
      .ThenInclude(join => join.Machine)
      .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
    var thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
    return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Linq;

namespace Factory.Controllers
{
  public class MachineController : Controller
  {
    private readonly FactoryContext _db;

    public MachineController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      var thisMachine = _db.Machines
      .Include(mach => mach.JoinEntities)
      .ThenInclude(join => join.Engineer);
      return View(thisMachine.ToList());
    }
    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }
    [HttpPost]
    public ActionResult Create (Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
      .Include(mach => mach.JoinEntities)
      .ThenInclude(join => join.Engineer)
      .FirstOrDefault(mach => mach.MachineId == id);
      return View(thisMachine);
    }
    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines
      .Include(mach => mach.JoinEntities)
      .ThenInclude(join => join.Engineer)
      .FirstOrDefault(mach => mach.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }
    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId, int joinId)
    {
      if (EngineerId != 0)
      {
        var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
        _db.EngineerMachine.Remove(joinEntry);    
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId});
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      return View(thisMachine);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }
    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineer/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a new engineer</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new engineer" />
}
<p>@Html.ActionLink("Show all engineers", "Index")</p>

Factory/Views/Engineer/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to remove this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to engineer list", "Index")

Factory/Views/Engineer/Details.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Engineer;

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<ul>
@if (@Model.JoinEntities.Count == 0)
{
  <p>This engineer hasn't been trained on any machines yet.</p>
}
else
{
  <h4>Machines this engineer is licensed to operate: </h4>
  @foreach(var join in @Model.JoinEntities)
  {
    <li>@Html.ActionLink($"{join.Machine.Name}", "Details", "Machines", new {id = join.MachineId})
      @using (Html.BeginForm("DeleteMachine", "Engineer"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete" />
    }
    </li>
  }
}
</ul>
<p>@Html.ActionLink("Add Machine", "Create", "Machine")</p>
<p>@Html.ActionLink("Back to Engineers", "Index")</p>
<p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>

Factory/Views/Engineer/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit</h2>
<h4>Edit this engineer: @Html.DisplayFor(model => model.Name)</h4>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <input type='submit' value='Save'/>
}
<p>@Html.ActionLink("Back to Engineers", "Index")</p>

Factory/Views/Engineer/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h1>Our Engineers:</h1>
  
@if (Model.Count == 0)
{
  <p>No one works here. Please hire some engineers.</p>
}

@foreach (Engineer engineer in Model)
{
  <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
}
<p>@Html.ActionLink("Add new engineer", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<h1>Dr. Sillystringz's Factory</h1>
<p>@Html.ActionLink("Check out our machines", "Index", "Machine")</p>
<p>@Html.ActionLink("Meet our engineers", "Index", "Engineer")</p>

Factory/Views/Machine/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine
<h2>Add a machine</h2>
<h4>Add a machine to this engineer's repertoire: @Html.DisplayFor(model => model.Name)</h4>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId")
  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to machine list", "Index")</p>

Factory/Views/Machine/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new Machine</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)

  <input type="submit" value="Add" class="btn btn-danger" />
}
<p>@Html.ActionLink("Show all machines", "Index")</p>

Factory/Views/Machine/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to remove this machine?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Scrap it" />
}
@Html.ActionLink("Back to machines", "Index")

Factory/Views/Machine/Details.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3><br>
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3><br>
<ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Engineer.Name</li>
    @using (Html.BeginForm("DeleteEngineer", "Machine"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete" />
    }
  }
</ul>
<hr />
<p>@Html.ActionLink("Back to machine list", "Index")</p>
<p>@Html.ActionLink("Edit machine", "Edit", new { id = Model.MachineId})</p>
<p>@Html.ActionLink("Remove machine", "Delete", new {id = Model.MachineId})
<p>@Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId })</p>

Factory/Views/Machine/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  @foreach (var join in Model.JoinEntities)
  {
      @Html.Hidden("joinId", @join.EngineerMachineId)
  }
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to machine list", "Index")</p>

Factory/Views/Machine/Index.cshtml
@{
  Layout = "_Layout";
}
@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Machine</h1>

@if (@Model.Count == 0)
{
  <h3>No machines have been added yet!</h3>
}

<ul>
@foreach (var machine in Model)
{
  <li>@Html.ActionLink($"{machine.Name}", "Details", new {id = machine.MachineId}) : 
    @foreach(var engineer in machine.JoinEntities)
    { 
      if (engineer.Engineer.Name != null)
      {
        <text> @engineer.Engineer.Name |</text>   
      }
    }
    @if (machine.JoinEntities.Count == 0)
    {
      <text>No one knows how to deal with this one.</text>
    }
  </li>
}
</ul>
<p>@Html.ActionLink("Add new machine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sillystringz Factory</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
      <div class="container">
        @RenderBody()
      </div>
  </body>
</html>